-- Nexiora AI — knowledge base RAG (Phase 3)
-- Adds real chunk-level embeddings for knowledge_documents, replacing the
-- Phase 2 shortcut of stuffing whole documents into every chat prompt.
-- Embeddings are generated by Supabase's built-in `gte-small` model (384
-- dimensions), run inside the embed-document Edge Function — no external
-- embeddings provider or API key needed.

create extension if not exists vector;

create table public.knowledge_chunks (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.orgs(id) on delete cascade,
  chatbot_id uuid not null references public.chatbots(id) on delete cascade,
  document_id uuid not null references public.knowledge_documents(id) on delete cascade,
  chunk_index integer not null,
  content text not null,
  embedding vector(384),
  created_date timestamptz not null default now()
);

create index knowledge_chunks_org_id_idx on public.knowledge_chunks(org_id);
create index knowledge_chunks_chatbot_id_idx on public.knowledge_chunks(chatbot_id);
create index knowledge_chunks_document_id_idx on public.knowledge_chunks(document_id);

-- HNSW index for fast cosine-similarity search. Fine to create against an
-- empty table — it builds incrementally as rows are inserted.
create index knowledge_chunks_embedding_idx on public.knowledge_chunks
  using hnsw (embedding vector_cosine_ops);

alter table public.knowledge_chunks enable row level security;

create policy "org members can read knowledge_chunks" on public.knowledge_chunks
  for select using (public.is_org_member(org_id));
create policy "org members can insert knowledge_chunks" on public.knowledge_chunks
  for insert with check (public.is_org_member(org_id));
create policy "org members can update knowledge_chunks" on public.knowledge_chunks
  for update using (public.is_org_member(org_id)) with check (public.is_org_member(org_id));
create policy "org members can delete knowledge_chunks" on public.knowledge_chunks
  for delete using (public.is_org_member(org_id));

-- Similarity search RPC used by the chat-completion Edge Function (called
-- with the service role, so RLS is bypassed there by design — the function
-- itself already checks org membership before this runs).
create or replace function public.match_knowledge_chunks(
  query_embedding vector(384),
  match_chatbot_id uuid,
  match_count int default 5
)
returns table (
  id uuid,
  document_id uuid,
  content text,
  similarity float
)
language sql
stable
as $$
  select
    knowledge_chunks.id,
    knowledge_chunks.document_id,
    knowledge_chunks.content,
    1 - (knowledge_chunks.embedding <=> query_embedding) as similarity
  from public.knowledge_chunks
  where knowledge_chunks.chatbot_id = match_chatbot_id
  order by knowledge_chunks.embedding <=> query_embedding
  limit match_count;
$$;
